version: '2'

services:
  jekyll:
    image: registry.cn-hangzhou.aliyuncs.com/solat/blog_jekyll
    volumes:
      - ${BLOG_APP}:/usr/local/blog
    environment:
      - JEKYLL_NEW=false
    ports:
      - '${PORT}:4000'
  
  jekyll-new:
    image: registry.cn-hangzhou.aliyuncs.com/solat/blog_jekyll
    volumes:
      - ${BLOG_APP}:/usr/local/blog
    environment:
      - JEKYLL_NEW=true
    ports:
      - '${PORT}:4000'
  
  jekyll-build:
    build:
      context: .
      args:
          - GWF=True