version: '2'

services:
  jekyll:
    image: registry.cn-hangzhou.aliyuncs.com/solat/blog_jekyll
    volumes:
      - .:/usr/local/blog
    environment:
      - JEKYLL_NEW=False
    ports:
      - '8080:4000'
  
  jekyll-init:
    jekyll:
    image: registry.cn-hangzhou.aliyuncs.com/solat/blog_jekyll
    volumes:
      - .:/usr/local/blog
    environment:
      - JEKYLL_NEW=True
    ports:
      - '8080:4000'
  
  jekyll-build:
    build:
      context: .
      args:
          - GWF=True